# Generated by Django 6.0 on 2026-01-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('xg_for', models.FloatField(default=0.0)),
                ('xg_against', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('xg', models.FloatField(default=0.0)),
                ('xag', models.FloatField(default=0.0)),
                ('progressive_carries', models.IntegerField(default=0)),
                ('progressive_passes', models.IntegerField(default=0)),
                ('tackles_won', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
        ),
    ]
