# Generated by Django 6.0.1 on 2026-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_goal_difference_team_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sofascore_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
