# Generated by Django 6.0.1 on 2026-01-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_sofascore_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
