# Generated by Django 6.0.1 on 2026-01-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
