# Generated by Django 6.0.1 on 2026-01-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_team_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='top_scorer_all_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
