# Generated by Django 6.0.1 on 2026-01-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_top_scorer_all_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fa_cup_titles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='league_cup_titles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='premier_league_titles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
