# Generated by Django 6.0.1 on 2026-01-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_matches_played_player_appearances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='savesInsideTheBox',
            new_name='savesShotsFromInsideTheBox',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='savesOutsideTheBox',
            new_name='savesShotsFromOutsideTheBox',
        ),
    ]
