# Generated by Django 6.0.1 on 2026-01-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_savesinsidethebox_player_savesshotsfrominsidethebox_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='xg',
            new_name='expectedGoals',
        ),
    ]
