# Generated by Django 6.0 on 2026-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.CharField(default='2023-24', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.CharField(default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('season', 'player_id')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('season', 'team_name')},
        ),
    ]
