# Generated by Django 6.0.1 on 2026-01-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_team_fa_cup_titles_team_league_cup_titles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='matches_played',
            new_name='appearances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AddField(
            model_name='player',
            name='errorLeadToGoal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='errorLeadToShot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goalsConceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goalsConcededInsideTheBox',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goalsConcededOutsideTheBox',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='highClaims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='savesInsideTheBox',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='savesOutsideTheBox',
            field=models.IntegerField(default=0),
        ),
    ]
