# Generated by Django 6.0.1 on 2026-01-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_xg_player_expectedgoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='expectedGoals',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
